simulation:
  init_size: 100
  max_size: 1000
  n_generations: 10
  n_traits: 3
  trait_min: -1
  trait_max: 1
  p_mut: 0.75
  mut_std: 0.1
  init_opt_gen:
    - 0
    - 0
    - 0
  sel_std: 1.2
  warm_rate: 0.001
  seed: 2137

grid_search:
  enabled: true
  mut_probs: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  mut_stds: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  n_simulations: 8

plotting:
  enabled: false

animation:
  enabled: false
  p_mut: 0.81
  mut_std: 0.81
  n_generations: 100